### ISSUE TITLE
W/com.adpdigital.push.GcmMessageHandler: Don't notify GCM when app is foreground!

### ISSUE THREAD

**Issue by ZahraSdg** [chabokpush/chabok-demo-android#10]
با وجود subscribe‌ کردن کانال هنوز نمیتونم پیام درون برنامه ای رو در وقت باز بودن برنامه دریافت کنم و وقتی لاگ رو میبینم این هست:
W/com.adpdigital.push.GcmMessageHandler: Don't notify GCM when app is foreground!
مشکل از کجاست؟

**Comment by behrad** [comment]
در زمانی که برنامه فورگراند هست شما پیام رو دریافت میکنید اما چابک نوتیفیکیشن رو نشون نمیده
این رفتار اولیه چابک هست که در نسخه‌های اولیه تصمیم بر اون گرفته شده است
اگر قصد دارید که در حالت فورگراند هم نوتیفیکیشن بیاد این رو می تونیم براتون در یک تنظیم انجام بدیم.

**Comment by Husseinhj** [comment]
> در حال حاضر اپ من با این که باز هست ولی در پنل انلاین نیست و به اصطلاح نوار سبز نمیخوره.

علت اینکه دستگاه شما به چابک متصل نمیشه این هست که متد رجیستر رو یکبار صدا میزنین. 
توی [داکیومنت](https://doc.chabokpush.com/android/application-class.html#%D8%AA%D9%88%D8%B6%DB%8C%D8%AD-%D9%85%D8%AA%D8%AF%D9%87%D8%A7) درموردش توضیح داده شده : 
`نکته`: هر بار که برنامه اجرا می‌شود لازم است این متد فراخوانی شود تا اتصال چابک برقرار گردد.

<div dir='rtl'>
متد رجیستر چابک کار اتصال به چابک رو هم انجام میده. یعنی به صورت عادی شما باید متد `register` چابک رو دوجا صدا بزنین. یکی در کلاس اپلیکیشن اندروید که همیشه فرخوانی میشه. به این صورت که اگر `userId` بود با userId یه چابک رجیستر می‌کنین اگه نبود هم تو صفحه لاگین اپلکیشن بعداز گرفتن `userId` کاربر متد رجیستر رو فراخوانی می‌کنین
</div>

همچنین عدم اتصال شما هم می‌تونه بخاطر استفاده از وی‌پی‌ان باشه. یکسری از وی‌پی‌ان‌ها یسری از پورت‌ها رو بستن که ممکنه پورت ما رو هم بسته باشن

> این تنظمات چگونه اس من باید انجام بدم یا از سمت شماست؟ و اینکه چقدر طول میکشه؟
<div dir='rtl'>
شما برای ارسال پوش‌نوتیفکیشن از گزینه تست نتیفیکیشن استفاده می‌کنین؟
چون پیام خود چابک نوتیفیکیشن نشون میده در حالت درون‌برنامه‌ای برای همین در حالت فورگراند تصمیم گرفتیم پوش‌نوتیفیکیشن گوگل رو نمایش ندیم. برای همین وقتی مشکل اتصال شما به چابک حل بشه وقتی اپ در حالت فورگراند باشه بصورت خودکار نوتفیکیشن نمایش خواهد داد.</div>

**Comment by Husseinhj** [comment]
این ایشو رو می‌بندم. در نسخه ۲.۱۲.۰ نمایش نوتیفیکیشن در فورگراند اضافه شده است.
