### ISSUE TITLE
دریافت پیام هنگامی که اپلیکیشن باز است.

### ISSUE THREAD

**Issue by sepehr13494** [chabokpush/chabok-demo-android#4]
با سلام در بخش ارسال پیام یک دکمه هستش که تایین میکنه وقتی که اپ روی گوشی کاربر باز است نوتیفیکیشن ارسال شود یا نه که با زدن این دکمه و ارسال پیام پیام در هنگام باز بودن اپ فرستاده نمیشود..

**Comment by Husseinhj** [comment]
اگه پیام برای شما در حالت درون برنامه‌ای نمیاد، مطمئن بشین که به چابک متصل هستید یا خیر

از طریق پنل مشترکین وقتی که دستگاه شما به چابک متصل باشه، باید یک نوار سبز رنگ بالا کارت دستگاه مشاهده کنید. که با وصل بودن دستگاه به چابک حتما باید پیام درون برنامه رو دریافت کنین

**Comment by sepehr13494** [comment]
الان پیام شخصی میفرسته تو هر ۲ حالت ولی پیم عمومی دیگه نمیفرسته.. معذرت
میخوا شما بخش مشاوره فنی دارین که بشه باهاش تماس گرفت؟

**Comment by sepehr13494** [comment]
من هرچقدر تلاش میکنم نمیتونم پیام عمومی رو وقتی که اپ بازه بفرستم کجا
میتونم در این رابطه اطلاعات بیشتری کسب کنم؟

**Comment by Husseinhj** [comment]
شما باید مفهوم کانال رو بدونین که به چه شکل هست. 
به صورت پاب/ساب عمل می‌کنیم. شما باید روی یکسری کانال (عمومی یا خصوصی) عضو بشین.

کانال‌ها یک درگاه ارتباطی أنی و سریع هستن. اگر میخواین کاربرها روی کانال عمومی عضو بشن باید روی کانال عمومی عوضشون کنین.

چابک به صورت پیش‌فرض روی یک کانال خصوصی هر کاربر رو عضو میکنه. برای فهمیدن نحوه استفاده از کانال کد زیر رو از داکیومنت مشاهده کنین :
[اندروید](https://doc.chabokpush.com/android/chabok-messaging.html#%D8%B9%D8%B6%D9%88%DB%8C%D8%AA-%D8%B1%D9%88%DB%8C-%DA%A9%D8%A7%D9%86%D8%A7%D9%84%D9%87%D8%A7) 

[ای او اس](https://doc.chabokpush.com/ios/publishingMessages.html#%D8%B9%D8%B6%D9%88%DB%8C%D8%AA-%D8%AF%D8%B1-%DA%A9%D8%A7%D9%86%D8%A7%D9%84)

لطفا داکیومنت رو مطالعه کنین اونجا جواب سوال شما هست.

[داکیومنت پنل ](https://doc.chabokpush.com/panel/send.html#%D9%85%D8%AE%D8%A7%D8%B7%D8%A8%D8%A7%D9%86-%D9%BE%DB%8C%D8%A7%D9%85)

**Comment by Husseinhj** [comment]
<div dir='rtl'>من این issue رو می‌بندم. اگر که مشکل شما حل نشد، مجددا issue رو باز کنین و در مورد مشکلتون بیشتر توضیح بفرمایید</div>
