### ISSUE TITLE
 نمایش  اعلان

### ISSUE THREAD

**Issue by AliRHp** [chabokpush/chabok-demo-android#5]
در تست اندروید ورژن 8 در گوشی mate 10 lite اعلان نمایش داده نمی شود

**Comment by Husseinhj** [comment]
<div dir='rtl'>نسخه BuildTools شما که باهاش Build می‌کنین چه نسخه‌ای هست؟</div>

**Comment by AliRHp** [comment]
buildToolsVersion "27.0.1"
        targetSdkVersion 27

**Comment by Husseinhj** [comment]
این ایشو رو می‌بندم چون این مسئله در نسخه 2.12.1 حل شده است.
