### ISSUE TITLE
اولین نوتیفیکیشن

### ISSUE THREAD

**Issue by sepehr13494** [chabokpush/chabok-demo-android#6]
با سلام میخواستم بپرسم میشه یه کاری کرد که نوتیفیکیشن به چابک خوش آمدید یا نیاد یا ادیت بشه؟

**Comment by Husseinhj** [comment]
برای تغییر متن پیام _خوش‌آمد_ و یا _غیرفعال_ کردن آن در پنل وارد صفحه **تنظیمات** و بخش **[پیام خوش‌آمد](https://sandbox.push.adpdigital.com/front/setting/setting/welcome)** شوید

**Comment by sepehr13494** [comment]
خیلی متشکر
