### ISSUE TITLE
محتوی غیر متنی

### ISSUE THREAD

**Issue by sepehr13494** [chabokpush/chabok-demo-android#7]
نحوه استفاده از محتوی غیر متنی چجوری هستش؟

**Comment by behrad** [comment]
شما هر دیتایی رو به صورت جیسان می‌تونید در کلید 
`data`
قرار بدید (یا در پنل در بخش مربوط جیسان‌تون رو بنویسیید)
و بعد داخل کلاینت از پیام دریافتی بخونیدش

**Comment by sepehr13494** [comment]
بعد امکانش هست که از طریق یه کلاینت دیگه ریکوئست زده بشه به سرور شما که
پیام رو بفرسته؟

**Comment by behrad** [comment]
> بعد امکانش هست که از طریق یه کلاینت دیگه ریکوئست زده بشه به سرور شما که
> پیام رو بفرسته؟

بله
شما در همه پلتفرم‌ها برای ارسال می تونید از 
`publishMessage` یا `publish`
استفاده کنید و لطفن مستندات رو بهتر مطالعه کنید

**Comment by sepehr13494** [comment]
خیلی ممنون بله حتما
