### ISSUE TITLE
عدم دریافت پیام هنگام بسته بودن برنامه

### ISSUE THREAD

**Issue by miladrasooli** [chabokpush/chabok-demo-android#8]
سلام ، وقتی برنامه رو کامل ببندم یعنی از توی حافظه هم پاک بشه دیگه نوتیفیکیشن دریافت نمیکنه ، مشکل از کجاست؟ مگر FCM وظیفه این کار رو بر عهده نداره؟

**Comment by behrad** [comment]
آیا تنظیمات جی‌سی‌ام رو روی پنل‌تون فعال کردین؟ این رو در بخش تنظیمات پنل می تونید تحقیق کنید

همچنین از منوی پیام‌ها داخل پنل پیامی که ارسال کردید وقتی برنامه بسته بوده رو پیدا کنید و جزییاتش رو چک کنید ببینید نوتیفیکیشنی که برای اون پیام رفته چه وضعیتی براش خورده

**Comment by miladrasooli** [comment]
بله تنظیمات GCM انجام شده و نوشته فعال است . توی جزییات پیام نوشته ارسال شده ولی دریافت شده نداره. یه مورد دیگه اینکه وقتی هم که برنامه توی بکگراند یا فورگراند باشه اگر پیام رو عمومی بفرستم دریافت نمیشه باید حتما یه سگمنت تعریف کنم تا دریافت بشه

**Comment by behrad** [comment]
> توی جزییات پیام نوشته ارسال شده ولی دریافت شده نداره

تصویر جزییات پیام تون رو برامون بگذارید
اگه نوتیفیکیشن تیک سبز خورده پس ارسالش موفق بوده و قاعدتن گوگل باید به گوشی رسونده باشتش و شما نوتیفیکیشن رو ببینی



> اگر پیام رو عمومی بفرستم دریافت نمیشه باید حتما یه سگمنت تعریف کنم تا دریافت بشه

برای پیام عمومی شما باید روی یک کانال عمومی عضو بشین بعد روی اون کانال ارسال کنید تا دریافت کنید

**Comment by miladrasooli** [comment]
به نظر میاد با استفاده از کانال عمومی اکی شد ، اما هنوز در صورت استفاده از پیام لحظه ای و درون برنامه ای نمیشه از دریافت پیام ها مطمئن بود بعضی وقتا دریافت میشه بعضی وقتا نمیشه

**Comment by behrad** [comment]
> اما هنوز در صورت استفاده از پیام لحظه ای و درون برنامه ای نمیشه از دریافت پیام ها مطمئن بود

تمام گزارشات رو می تونید برای هر پیام مشاهده کنید و از همه چیز مطمئن باشید

باید بررسی کنید و با دقت ببینید کدوم شرایط رو دارید تست می کنید.
پیام لحظه‌ای با مدل برودکست کار میکنه و فقط به کاربران آنلاین میرسه

اما پیام‌های دیگه حتمن باید برسه و به هیچ عنوان گم نمیشن
هندلر دریافت پیامتون رو توی اپ بررسی کنید و از پنل وضعیت پیام‌ها رو چک کنید همزمان
